# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 01:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('permanent_address', models.TextField(max_length=500)),
                ('temporary_address', models.TextField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='companyadmin',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employeemodel',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanyAdmin',
        ),
        migrations.DeleteModel(
            name='EmployeeModel',
        ),
    ]
